VaishaliLiftoff/Models/Student.cs
using System.Collections.Generic;

namespace InstituteAdministration.Models
{
    public class Student
    {
        public int Id { get; set; }

        public string Name { get; set; } = null!;

        public Teacher Teacher { get; set; } = null!;

        public int TeacherId { get; set; }

        public List<StudentCourse> StudentCourses { get; set; } = null!;

    }
}

VaishaliLiftoff/Controllers/ListController.cs
using InstituteAdministration.Data;
using InstituteAdministration.Models;
using InstituteAdministration.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;

namespace InstituteAdministration.Controllers
{
    public class ListController : Controller
    {
        internal static Dictionary<string, string> ColumnChoices = new Dictionary<string, string>()
        {
            {"all", "All"},
            {"teacher", "Teacher"},
            {"course", "Course"}
        };

        internal static List<string> TableChoices = new List<string>()
        {
            "teacher",
            "course"
        };

        private StudentDbContext context;

        public ListController(StudentDbContext dbContext)
        {
            context = dbContext;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
            ViewBag.columns = ColumnChoices;
            ViewBag.tablechoices = TableChoices;
            ViewBag.teachers = context.Teachers.ToList();
            ViewBag.courses = context.Courses.ToList();
            return View();
        }

        // list jobs by column and value
        public IActionResult Students(string column, string value)
        {
            List<Student> students = new List<Student>();
            List<StudentDetailViewModel> displayStudents = new List<StudentDetailViewModel>();

            if (column.ToLower().Equals("all"))
            {
                students = context.Students
                    .Include(j => j.Teacher)
                    .ToList();

                foreach (var student in students)
                {
                    List<StudentCourse> studentCourses = context.StudentCourses
                        .Where(js => js.StudentId == student.Id)
                        .Include(js => js.Course)
                        .ToList();

                    StudentDetailViewModel newDisplayStudent = new StudentDetailViewModel(student, studentCourses);
                    displayStudents.Add(newDisplayStudent);
                }

                ViewBag.title = "All Students";
            }
            else
            {
                if (column == "teacher")
                {
                    students = context.Students
                        .Include(j => j.Teacher)
                        .Where(j => j.Teacher.Name == value)
                        .ToList();

                    foreach (Student student in students)
                    {
                        List<StudentCourse> studentCourses = context.StudentCourses
                        .Where(js => js.StudentId == student.Id)
                        .Include(js => js.Course)
                        .ToList();

                        StudentDetailViewModel newDisplayStudent = new StudentDetailViewModel(student, studentCourses);
                        displayStudents.Add(newDisplayStudent);
                    }
                }
                else if (column == "course")
                {
                    List<StudentCourse> studentCourses = context.StudentCourses
                        .Where(j => j.Course.Name == value)
                        .Include(j => j.Student)
                        .ToList();

                    foreach (var student in studentCourses)
                    {
                        Student foundStudent = context.Students
                            .Include(j => j.Teacher)
                            .Single(j => j.Id == student.StudentId);

                        List<StudentCourse> displayCourses = context.StudentCourses
                            .Where(js => js.StudentId == foundStudent.Id)
                            .Include(js => js.Course)
                            .ToList();

                        StudentDetailViewModel newDisplayStudent = new StudentDetailViewModel(foundStudent, displayCourses);
                        displayStudents.Add(newDisplayStudent);
                    }
                }
                ViewBag.title = "Students with " + ColumnChoices[column] + ": " + value;
            }
            ViewBag.students = displayStudents;

            return View();
        }
    }
}

VaishaliLiftoff/Views/List/Index.cshtml
<div class="container body-content">
    <h1>@ViewBag.title</h1>
    <h2 class="centered">View Students By Category</h2>
</div>

<table class="centeredTable">
    <tr>
        @foreach (var column in ViewBag.columns)
        {
            @if (column.Key != "all")
            {
                <th>@column.Value</th>
            }
        }
    </tr>
    <tr>
        @foreach (var category in ViewBag.tableChoices)
        {
            <td>
                <ul>
                    @if (category == "teacher")
                    {
                        @foreach (var item in ViewBag.teachers)
                        {
                            <li>
                                <a asp-controller="List" asp-action="Students" asp-route-column="@category" asp-route-value="@item.Name">@item.Name</a>
                            </li>
                        }
                    }
                    else
                    {
                        @foreach (var item in ViewBag.courses)
                        {
                            <li>
                                <a asp-controller="List" asp-action="Students" asp-route-column="@category" asp-route-value="@item.Name">@item.Name</a>
                            </li>
                        }
                    }

                </ul>
            </td>
        }
    </tr>
</table>

VaishaliLiftoff/Views/List/Student.cshtml
<div class="container body-content">

    <h1>@ViewBag.title</h1>

    <table>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Teacher</th>
            <th>Courses</th>
        </tr>
        @foreach (var job in ViewBag.students)
        {
            <tr>
                <td>@job.StudentId</td>
                <td>@job.Name</td>
                <td>@job.TeacherName</td>
                <td>@job.CourseText</td>
            </tr>
        }
    </table>

</div>

VaishaliLiftoff/Views/List/Students.cshtml
<div class="container body-content">

    <h1>@ViewBag.title</h1>

    <table>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Teacher</th>
            <th>Courses</th>
        </tr>
        @foreach (var job in ViewBag.students)
        {
            <tr>
                <td>@job.StudentId</td>
                <td>@job.Name</td>
                <td>@job.TeacherName</td>
                <td>@job.CourseText</td>
            </tr>
        }
    </table>

</div>